services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: development
        OPCACHE_DEFAULT: 0
    environment:
      - 'SENTRY_LARAVEL_DSN=null'
      - 'SENTRY_TRACES_SAMPLE_RATE=1.0'
    volumes:
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./resources:/var/www/html/resources
      - ./public:/var/www/html/public
      - ./routes:/var/www/html/routes
      - ./vite.config.js:/var/www/html/vite.config.js
      - ./storage/logs/laravel.log:/var/www/html/storage/logs/laravel.log
    ports:
      - "${APP_PORT:-8000}:8080"
  # typesense:
  #   environment:
  #     TYPESENSE_LOG_LEVEL: debug
  #   ports:
  #     - "${TYPESENSE_PORT:-8108}:8108"
